import { cmsUrl } from "@/constants";
import useTours from "@/hooks/useTours";
import Head from "next/head";
import Link from "next/link";
import { Card, Col, Container, Row, Spinner } from "react-bootstrap";

export default function Home() {
  const { data, isLoading } = useTours();
  const tours = data?.data;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-4">
        <Container>
          <h1>Home Page</h1>
          {isLoading ? (
            <Spinner variant="primary" />
          ) : (
            <Row>
              {tours.map((tour) => {
                const { id, title, shortDescription, slug, heroImage } =
                  tour.attributes;

                const imagePath = heroImage?.data?.attributes?.url;
                const imageUrl = imagePath ? `${cmsUrl}${imagePath}` : null;

                return (
                  <Col xs={12} md={6} lg={4} key={id}>
                    <Link
                      href={`/tour/${slug}`}
                      className="text-decoration-none"
                    >
                      <Card className="h-100">
                        <Card.Img
                          variant="top"
                          src={imageUrl}
                          className="h-220px object-fit-cover"
                        />
                        <Card.Body className="">
                          <Card.Title className="text-dark">{title}</Card.Title>
                          <Card.Text className="text-dark">
                            {shortDescription}
                          </Card.Text>
                          {/* <Button variant="primary">Go somewhere</Button> */}
                        </Card.Body>
                      </Card>
                    </Link>
                  </Col>
                );
              })}
            </Row>
          )}
        </Container>
      </main>
    </>
  );
}
